### ISSUE TITLE
Add "prompt" function

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#13]
Add a function that can accept input from the user. It would specify the variable name to store the result and optional text for the prompt.

```yaml
steps:
  - prompt:
      for: firstName
      text: What is your first name?
  - log: Your first name is $firstName
```

If the prompt value is already set, then no prompt should be displayed. This way, the data could be passed in via a context file.
