### ISSUE TITLE
Add "toBase64" and "fromBase64" functions

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#16]
```yaml
steps:
  - decoded = fromBase64: $encoded
  - encodedAgain = toBase64: $decoded
  - asAscii = fromBase64:
      value: $encoded
      as: ascii
```

Could be part of an "encoding" module. Assume "from" or "to" is "utf-8" unless specified.
