### ISSUE TITLE
Add "date" function

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#20]
Accepts string parameter and returns a Date object.

Would help for running assertions on SQL results that have dates:

```yaml
- contains:
    in: $sqlResults
    value:
      name: John Smith
      birthDate: $date('1/1/1977')
```
