### ISSUE TITLE
Reference "partial" scripts

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#24]
Pumlhorse should allow "partial" scripts that can be called by other scripts. These would be common steps that could be shared across multiple scripts. However, they should not get picked up as normal scripts when running a directory.

Something like:

```yaml
name: Call a partial script
steps:
  - run: ../partials/login.puml.partial # Maybe ".puml.partial" can be assumed here
  - run: 
      script: ../partials/loginWithParameters.puml.partial
      with: # These values would be passed to the partial script
        username: jsmith
        password: hunter2
  - run:
      script: ../partials/loginWithScope.puml.partial
      shareScope: true
```

Then the partials would just be normal Pumlhorse formats
