### ISSUE TITLE
Add ability to filter which scripts to run

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#27]
Should be able to define some sort of filter to include/exclude scripts from running. For instance, a profile might look like:

```yaml
contexts:
  - ./contexts/context.prod.yaml
include:
  - ./test_dir
exclude tags:
  - non-prod
```

Conceivably this would block any scripts that have a "tag" of `non-prod` from running.

More thought needed about how flexible this should be. Go off a single `tags` property? Be able to check any property in the script?

**Comment by mdickin** [comment]
Would also want to exclude certain files, especially given the new support for partial files.

Another option:
```yaml
include:
  -  ./test_dir
exclude:
  filenames:
    - *.partial.puml
  directories:
    - secret_dir1
    - secret_dir2
  attributes:
    - tag = non-prod
    - author = john.doe
```
