### ISSUE TITLE
Add ability to set default headers for HTTP calls

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#30]
Should be able to set default headers for HTTP calls in a script.

```yaml
- http.defaultHeaders:
    Authorization: Basic XXXXXX
    X-TestVal: myTestVal2
```

May want a simplified function to set authorization.

```yaml
# Option 1
- http.setAuthorization: Basic XXXX
# Option 2
- http.setBasicAuthorization:
    username: $username
    password: $password
```
