### ISSUE TITLE
"If" function writes unnecessary warning

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#44]
Consider the following steps:

```yaml
- if:
    value: ${ 1 == 0 }
    is true:
      - fail: Uhh, you might want to check again
- log: Whew, that passed
```

In this case, we only want to specify `is true`, but the expression is not true. It will continue on to the next step, but not before logging "Script does not contain any steps". This is because it tries to call `$scope._run(null)`. There is no need to call `$scope._run` in this case.
