### ISSUE TITLE
Add a function to filter arrays easily

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#45]
```yaml
# Filter $persons array to objects with type == user
- results = filter:
    array: $persons
    on:
      type: user
```

**Comment by mdickin** [comment]
Maybe a sort too:

```yaml
- results = sort:
    array: $persons
    by:
      - name
      - -age
      - body.eyeColor
```

Would sort by name in ascending order, then by age in descending order, then body.eyeColor
