### ISSUE TITLE
Add "switch" capabilities to "if" function

### ISSUE THREAD

**Issue by mdickin** [pumlhorse/pumlhorse#5]
Something like

```yaml
name: Use switch syntax
steps:
  - x = 3
  - if:
    value: $x
    is 1:
      - log: One
    is 2:
      - log: Two
    is 3:
      - log: Three #Hits this
    == 3:
      - log: Equals three #Also hits this
    < 0:
      - log: Negative
    > 0:
      - log: Positive #Also hits this
```

basically, the key would be parsed as an Angular expression, replacing "is " with "==". This would allow "is true" and "is false" to still behave as normal.
